### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by RiverTam57** [HackTrain/HackTrain#1]
**OVERALL**

Very very happy with it. Great sizing. Great choice of fonts for the text. Nice colours too.

**HEADER**

The header should be carousel. Have 3-4 different images with text.

1: General what HackTrain is
2: The trial with Chiltern
3: The trial with VTEC
4: The hackathon and application links for it

Sarah has written content for the first 3 I think....

**FONTS**

Please change the fonts for the boxes of "APPLY: EUROPEAN HACKTRAIN" and "APPLY: Hong Kong HackTrain"

**SERVICES**
This is probably the weakest of all sections.

It's too easy... Not emotional enough. Doesn't show us off as much as we want to...

It should be a lot more visually compelling. Let's add in some really powerful imagery here. 

**Our Work**

Should be some text overlayed onto it so people know what it's about. 

Maybe reduce it to 6 and make the images bigger/aligned differently? It should be clickable to another page for people to read more about the work we've done.

**TEAM**

Let's add an introductory paragraph about how we KNOW tech. We are technology specialists in rail. 

**Get In Touch**

This is fairly weak too... Let's see what other sites have done.

**Comment by markwilliamfirth** [comment]
@RiverTam57 I have extracted and separately posted the website issues, closing this issue
